### ISSUE TITLE
Kernel build failing

### ISSUE THREAD

**Issue by fcladera** [compulab-yokneam/meta-compulab-bsp#6]
I am following the instructions from https://github.com/compulab-yokneam/meta-compulab-bsp/blob/devel-imx8mm-4.14.98/Documentation/linux_kernel_build.md to buld the kernel, and the following error message appears:

```
make: Entering directory '/samsungSSD/debian/kernelCompile/imx8mm/linux-imx'
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CHK     include/generated/bounds.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
  HOSTLD  scripts/dtc/dtc
/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [scripts/Makefile.host:111: scripts/dtc/dtc] Error 1
make[1]: *** [scripts/Makefile.build:585: scripts/dtc] Error 2
make: *** [Makefile:572: scripts] Error 2
make: Leaving directory '/samsungSSD/debian/kernelCompile/imx8mm/linux-imx'
```
Any help is greatly appreciated!

**Comment by kkapranov** [comment]
Hi Fernando,

The root of the problem lies in different default build options of different compilers: some suppose default  –fcommon, others (e.g. GCC 10.x) suppose –fno-common.
To fix this issue please apply the patch [1]:
Issue in the Linux source tree:
`git cherry-pick e33a814e772cdc36436c8c188d8c42d019fda639
`
[1] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=e33a814e772cdc36436c8c188d8c42d019fda639&h=linux-4.14.y

**Comment by fcladera** [comment]
After applying the patch, I am facing the following error. Unsure if it is the same related bug:
```
make: Entering directory '/samsungSSD/devster/debian/kernelCompile/linux-imx'
  CHK     include/config/kernel.release
  UPD     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  UPD     include/generated/utsrelease.h
  CHK     include/generated/bounds.h
  CHK     include/generated/timeconst.h
/bin/sh: 1: bc: not found
Kbuild:43: recipe for target 'include/generated/timeconst.h' failed
make[1]: *** [include/generated/timeconst.h] Error 127
Makefile:1084: recipe for target 'prepare0' failed
make: *** [prepare0] Error 2
make: Leaving directory '/samsungSSD/debian/kernelCompile/linux-imx'
```

**Comment by kkapranov** [comment]
Issue bc on a command line in order to  check that bc calculator utility is installed on the build host and may be called.

**Comment by fcladera** [comment]
Trap for young players... I should have checked it first. Thanks, that fixed it.

**Comment by vraevsky** [comment]
Fixed
