### ISSUE TITLE
systemd_%25.bbappend causes build failure during do_install

### ISSUE THREAD

**Issue by mwsoverdick** [compulab-yokneam/meta-compulab-bsp#7]
https://github.com/compulab-yokneam/meta-compulab-bsp/blob/6c9153f09aeb98e7970341828ad98d4b58b4536d/meta-bsp/recipes-bsp/systemd/systemd_%25.bbappend#L6

I believe the `/image` needs to be removed after `${D}` as it is calling build failures in Yocto 3.1.7:

get error returned from `sed`: No such files or directory

Full output from `sed` shows:
`sed: can't read tmp/work/aarch64-fslc-linux/systemd/1_244.5-r0/image/image/lib/systemd/system/systemd-rfkill.service: No such file or directory`

As you can see, there is `image/image` created by the systemd .bbappend file in `meta-compulab-bsp`

removing `/image` from the .bbappend file resolved the issue for me.

**Comment by vraevsky** [comment]
Thanks for reporting on the issue.
Fix is applied:https://github.com/compulab-yokneam/meta-compulab-bsp/commit/95073b239d0ea80d3ba133c1346421dba5811dd9
